Table:
  Type: 'AWS::DynamoDB::Table'
  DeletionPolicy: Retain
  DependsOn: DalaWalletsDynamoDbTable
  Properties:
    AttributeDefinitions:
      -
        AttributeName: address
        AttributeType: S
      -
        AttributeName: savingsId
        AttributeType: N
      -
        AttributeName: username
        AttributeType: S
    KeySchema:
        -
          AttributeName: address
          KeyType: HASH
    ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
    TableName: 'FineractSavingsAccounts'
    GlobalSecondaryIndexes:
      -
        IndexName: idx_fineractSavingsAccounts_savingsId
        KeySchema:
          -
            AttributeName: savingsId
            KeyType: HASH
        Projection:
          ProjectionType: ALL
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
      -
        IndexName: idx_fineractSavingsAccounts_username
        KeySchema:
          -
            AttributeName: username
            KeyType: HASH
        Projection:
          ProjectionType: ALL
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    StreamSpecification:
      StreamViewType: 'NEW_AND_OLD_IMAGES'