Key:
  Type: AWS::KMS::Key
  DependsOn: IamRoleLambdaExecution
  Properties:
    Description: "KMS key for encryption of blockchain resources such as private key"
    Enabled: true
    KeyPolicy:
      Version: '2012-10-17'
      Id: 'dala-wallet-key'
      Statement:
        -
          Sid: "Enable IAM User Permissions"
          Effect: "Allow"
          Principal: 
            AWS: "arn:aws:iam::${env:AWS_ACCOUNT_ID}:root"
          Action: "kms:*"
          Resource: "*"
        -
          Sid: "Allow use of the key"
          Effect: "Allow"
          Principal: 
            AWS: "arn:aws:iam::${env:AWS_ACCOUNT_ID}:role/dala-wallet-api-${self:provider.stage}-${self:provider.region}-lambdaRole"
          Action: 
            - "kms:Encrypt"
            - "kms:Decrypt"
            - "kms:ReEncrypt*"
            - "kms:GenerateDataKey*"
            - "kms:DescribeKey"
          Resource: "*"