StateMachine:
  Type: AWS::StepFunctions::StateMachine
  Properties:
    DefinitionString: |-
      {
        "StartAt":"Processing",
        "States":{
          "Processing":{
            "Type":"Task",
            "ResultPath":"$.processingResult",
            "Resource":"arn:aws:lambda:${self:provider.region}:${env:AWS_ACCOUNT_ID}:function:dala-wallet-api-${self:provider.stage}-walletProcessing",
            "Catch":[
              {
                "ErrorEquals":[
                  "ItemAlreadyExistsError", 
                  "InvalidStatusError"
                ],
                "ResultPath":"$.error",
                "Next":"End"
              },
              {
                "ErrorEquals":[
                  "States.TaskFailed"
                ],
                "ResultPath":"$.error",
                "Next":"Failed"
              }
            ],
            "Retry":[
              {
                "ErrorEquals":[
                  "ItemAlreadyExistsError", 
                  "InvalidStatusError"
                ],
                "MaxAttempts":0
              },
              {
                "ErrorEquals": [
                    "States.TaskFailed"
                ],
                "IntervalSeconds": 1,
                "MaxAttempts": 2,
                "BackoffRate": 2.0
              }
            ],
            "Next":"Create Wallet On Chain"
          },
          "Create Wallet On Chain":{
            "Type":"Task",
            "Resource":"arn:aws:lambda:${self:provider.region}:${env:AWS_ACCOUNT_ID}:function:dala-wallet-api-${self:provider.stage}-ethCreateWallet",
            "ResultPath":"$.createWalletResult",
            "Catch":[
              {
                "ErrorEquals":[
                  "States.TaskFailed"
                ],
                "ResultPath":"$.error",
                "Next":"Failed"
              }
            ],
            "Next":"Get Transaction Receipt"
          },
          "Get Transaction Receipt":{
            "Type":"Task",
            "InputPath":"$.createWalletResult.transactionHash",
            "ResultPath":"$.transactionReceipt",
            "Resource":"arn:aws:lambda:${self:provider.region}:${env:AWS_ACCOUNT_ID}:function:dala-wallet-api-${self:provider.stage}-ethGetTransactionReceipt",
            "Retry":[
              {
                "ErrorEquals": [
                  "TransactionNotCompleteError"
                ],
                "MaxAttempts":0
              },
              {
                "ErrorEquals": [
                  "TransactionFailedError"
                ],
                "MaxAttempts":0
              },
              {
                "ErrorEquals": [
                    "States.TaskFailed"
                ],
                "IntervalSeconds": 1,
                "MaxAttempts": 2,
                "BackoffRate": 2.0
              }
            ],
            "Catch":[
              {
                "ErrorEquals": [
                  "TransactionNotCompleteError"
                ], 
                "ResultPath": "$.transactionNotComplete",
                "Next": "Wait"
              },
              {
                "ErrorEquals": [
                  "TransactionFailedError"
                ], 
                "ResultPath": "$.transactionFailed",
                "Next": "Failed"
              }
            ],
            "Next":"Created"
          },
          "Wait":{
            "Type":"Wait",
            "Seconds":10,
            "Next":"Get Transaction Receipt"
          },
          "Created":{
            "Type":"Task",
            "ResultPath":"$.createdResult",
            "Resource":"arn:aws:lambda:${self:provider.region}:${env:AWS_ACCOUNT_ID}:function:dala-wallet-api-${self:provider.stage}-walletCreated",
            "Retry":[
              {
                "ErrorEquals": [
                    "States.TaskFailed"
                ],
                "IntervalSeconds": 1,
                "MaxAttempts": 2,
                "BackoffRate": 2.0
              }
            ],
            "Next":"Notify Success"
          },
          "Failed":{
            "Type":"Task",
            "ResultPath":"$.failedResult",
            "Resource":"arn:aws:lambda:${self:provider.region}:${env:AWS_ACCOUNT_ID}:function:dala-wallet-api-${self:provider.stage}-walletFailed",
            "Retry":[
              {
                "ErrorEquals": [
                    "States.TaskFailed"
                ],
                "IntervalSeconds": 1,
                "MaxAttempts": 2,
                "BackoffRate": 2.0
              }
            ],
            "Next":"Notify Failure"
          },
          "Notify Success":{
            "Type":"Task",
            "Resource":"arn:aws:lambda:${self:provider.region}:${env:AWS_ACCOUNT_ID}:function:dala-wallet-notifications-api-${self:provider.stage}-onSuccessfulCreateOnChainWallet",
            "Retry":[
              {
                "ErrorEquals": [
                    "States.TaskFailed"
                ],
                "IntervalSeconds": 1,
                "MaxAttempts": 2,
                "BackoffRate": 2.0
              }
            ],
            "Catch":[
              {
                "ErrorEquals":[
                  "States.TaskFailed"
                ],
                "ResultPath":"$.error",
                "Next":"End"
              }
            ],
            "End":true
          },
          "Notify Failure":{
            "Type":"Task",
            "Resource":"arn:aws:lambda:${self:provider.region}:${env:AWS_ACCOUNT_ID}:function:dala-wallet-notifications-api-${self:provider.stage}-onFailedCreateOnChainWallet",
            "Retry":[
              {
                "ErrorEquals": [
                    "States.TaskFailed"
                ],
                "IntervalSeconds": 1,
                "MaxAttempts": 2,
                "BackoffRate": 2.0
              }
            ],
            "Catch":[
              {
                "ErrorEquals":[
                  "States.TaskFailed"
                ],
                "ResultPath":"$.error",
                "Next":"End"
              }
            ],
            "End":true
          },
          "End":{
            "Type":"Pass",
            "End":true
          }
        }
      }
    RoleArn: { "Fn::GetAtt": ["DalaWalletStateMachineExecutionRole", "Arn"] } 