StateMachine:
  Type: AWS::StepFunctions::StateMachine
  Properties:
    DefinitionString: |-
      {
        "StartAt":"Send Notification",
        "States": {
          "Send Notification":{
            "Type":"Task",
            "Resource":"arn:aws:lambda:${self:provider.region}:${env:AWS_ACCOUNT_ID}:function:dala-wallet-api-${self:provider.stage}-sendNotification",
            "End":true
          }
        }
      }
    RoleArn: { "Fn::GetAtt": ["DalaWalletStateMachineExecutionRole", "Arn"] } 