StateMachine:
  Type: AWS::StepFunctions::StateMachine
  Properties:
    DefinitionString: |-
      {
        "StartAt":"Processing",
        "States": {
          "Processing":{
            "Type":"Task",
            "Resource":"",
            "Next":"Sweep Tokens"
          },
          "Sweep Tokens":{
            "Type":"Task",
            "Resource":"",
            "Next":"Transfer"
          },
          "Transfer":{
            "Type":"Task",
            "Resource":"",
            "Next":"Complete"
          },
          "Complete":{
            "Type":"Task",
            "Resource":"",
            "End":true
          }
        }
      }
    RoleArn: { "Fn::GetAtt": ["DalaWalletStateMachineExecutionRole", "Arn"] } 