StateMachine:
  Type: AWS::StepFunctions::StateMachine
  Properties:
    DefinitionString: |-
      {
        "StartAt":"Create Fineract Client",
        "States":{
          "Create Fineract Client":{
            "Type":"Task",
            "ResultPath":"$.fineractClient",
            "Resource":"arn:aws:lambda:${self:provider.region}:${env:AWS_ACCOUNT_ID}:function:dala-wallet-api-${self:provider.stage}-finCreateClient",
            "Retry":[
              {
                "ErrorEquals": [
                    "States.TaskFailed"
                ],
                "IntervalSeconds": 1,
                "MaxAttempts": 2,
                "BackoffRate": 2.0
              }
            ],
            "Next":"Create Fineract Account"
          },
          "Create Fineract Account":{
            "Type":"Task",
            "ResultPath":"$.fineractAccount",
            "Resource":"arn:aws:lambda:${self:provider.region}:${env:AWS_ACCOUNT_ID}:function:dala-wallet-api-${self:provider.stage}-finCreateAccount",
            "Retry":[
              {
                "ErrorEquals": [
                    "States.TaskFailed"
                ],
                "IntervalSeconds": 1,
                "MaxAttempts": 2,
                "BackoffRate": 2.0
              }
            ],
            "Next":"Approve Fineract Account"
          },
          "Approve Fineract Account":{
            "Type":"Task",
            "ResultPath":"$.fineractApproved",
            "Resource":"arn:aws:lambda:${self:provider.region}:${env:AWS_ACCOUNT_ID}:function:dala-wallet-api-${self:provider.stage}-finApproveAccount",
            "Retry":[
              {
                "ErrorEquals": [
                    "States.TaskFailed"
                ],
                "IntervalSeconds": 1,
                "MaxAttempts": 2,
                "BackoffRate": 2.0
              }
            ],
            "Next":"Activate Fineract Account"
          },
          "Activate Fineract Account":{
            "Type":"Task",
            "ResultPath":"$.fineractApproved",
            "Resource":"arn:aws:lambda:${self:provider.region}:${env:AWS_ACCOUNT_ID}:function:dala-wallet-api-${self:provider.stage}-finActivateAccount",
            "Retry":[
              {
                "ErrorEquals": [
                    "States.TaskFailed"
                ],
                "IntervalSeconds": 1,
                "MaxAttempts": 2,
                "BackoffRate": 2.0
              }
            ],
            "Next":"Set Values"
          },
          "Set Values":{
            "Type":"Parallel",
            "ResultPath":"$.setClientValuesResults",
            "End":true,
            "Branches":[
              {
                "StartAt":"Set Client Id",
                "States":{
                  "Set Client Id":{
                    "Type":"Task",
                    "Resource":"arn:aws:lambda:${self:provider.region}:${env:AWS_ACCOUNT_ID}:function:dala-wallet-api-${self:provider.stage}-userSetClientId",
                    "Retry":[
                      {
                        "ErrorEquals": [
                            "States.TaskFailed"
                        ],
                        "IntervalSeconds": 1,
                        "MaxAttempts": 2,
                        "BackoffRate": 2.0
                      }
                    ],
                    "End":true
                  }
                }
              },
              {
                "StartAt":"Set Default Account Id",
                "States":{
                  "Set Default Account Id":{
                    "Type":"Task",
                    "Resource":"arn:aws:lambda:${self:provider.region}:${env:AWS_ACCOUNT_ID}:function:dala-wallet-api-${self:provider.stage}-userSetDefaultAccountId",
                    "Retry":[
                      {
                        "ErrorEquals": [
                            "States.TaskFailed"
                        ],
                        "IntervalSeconds": 1,
                        "MaxAttempts": 2,
                        "BackoffRate": 2.0
                      }
                    ],
                    "End":true
                  }
                }
              },
              {
                "StartAt":"Set Default Account Address",
                "States":{
                  "Set Default Account Address":{
                    "Type":"Task",
                    "Resource":"arn:aws:lambda:${self:provider.region}:${env:AWS_ACCOUNT_ID}:function:dala-wallet-api-${self:provider.stage}-userSetDefaultAccountAddress",
                    "Retry":[
                      {
                        "ErrorEquals": [
                            "States.TaskFailed"
                        ],
                        "IntervalSeconds": 1,
                        "MaxAttempts": 2,
                        "BackoffRate": 2.0
                      }
                    ],
                    "End":true
                  }
                }
              }
            ]
          }
        }
      }
    RoleArn: { "Fn::GetAtt": ["DalaWalletStateMachineExecutionRole", "Arn"] } 