version: 0.2
env:
  variables:
    AWS_PROFILE: mainnet
  parameter-store:
    AWS_ACCESS_KEY_ID: SERVERLESS_MAINNET_AWS_ACCESS_KEY
    AWS_SECRET_ACCESS_KEY: SERVERLESS_MAINNET_AWS_ACCESS_SECRET
    AWS_ACCOUNT_ID: MAINNET_ACCOUNTID
    SLACK_WEBHOOK: MAINNET_SLACK_URL
phases:
  install:
    commands: 
      - npm install -g yarn
      - npm install -g serverless
      - cd / && serverless config credentials --provider aws --key $AWS_ACCESS_KEY_ID --secret $AWS_SECRET_ACCESS_KEY --profile mainnet
  pre_build:
    commands:
      - echo 'serverless version -' `serverless --version`
      - cd $CODEBUILD_SRC_DIR
  build:
    commands:
      - yarn
      - cp -f serverless/base/serverless.yml .
      - serverless deploy --stage mainnet --profile mainnet
      - cp -f serverless/notifications/serverless.yml .
      - serverless deploy --stage mainnet --profile mainnet
      - cp -f serverless/logging/serverless.yml .
      - serverless deploy --stage mainnet --profile mainnet
      - cp -f serverless/support/serverless.yml .
      - serverless deploy --stage mainnet --profile mainnet
  post_build:
    commands:
artifacts:
  files: 
    - '**/*'
