version: 0.2
env:
  variables:
    AWS_PROFILE: sandbox
  parameter-store:
    AWS_ACCESS_KEY_ID: SERVERLESS_SANDBOX_AWS_ACCESS_KEY
    AWS_SECRET_ACCESS_KEY: SERVERLESS_SANDBOX_AWS_ACCESS_SECRET
    AWS_ACCOUNT_ID: SANDBOX_ACCOUNTID
    SLACK_WEBHOOK: ROPSTEN_SLACK_URL
phases:
  install:
    commands: 
      - npm install -g yarn
      - npm install -g serverless
      - cd / && serverless config credentials --provider aws --key $AWS_ACCESS_KEY_ID --secret $AWS_SECRET_ACCESS_KEY --profile sandbox
  pre_build:
    commands:
      - echo 'serverless version -' `serverless --version`
      - cd $CODEBUILD_SRC_DIR
  build:
    commands:
      - yarn
      - cp -f serverless/base/serverless.yml .
      - serverless deploy --stage dev --profile sandbox
      - cp -f serverless/notifications/serverless.yml .
      - serverless deploy --stage dev --profile sandbox
  post_build:
    commands:
artifacts:
  files: 
    - '**/*'
